when:
  - event: [pull_request, tag, cron]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &platforms "linux/amd64,linux/arm64"

steps:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx:2.3.0
    settings:
      dockerfile: Dockerfile
      dry_run: true
      repo: woodpeckerci/plugin-codecov
      tag: test
    when:
      event: pull_request

  publish-next:
    image: woodpeckerci/plugin-docker-buildx:2.3.0
    settings:
      dockerfile: Dockerfile
      repo: woodpeckerci/plugin-codecov
      tags: next
    secrets: [docker_username, docker_password]
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  publish-tag:
    image: woodpeckerci/plugin-docker-buildx:2.3.0
    settings:
      dockerfile: Dockerfile
      auto_tag: true
      platforms: *platforms
      repo: woodpeckerci/plugin-codecov
    secrets: [docker_username, docker_password]
    when:
      event: tag
