variables:
  - &golang_image 'docker.io/golang:1.24'
  - &when
    - path: &when_path # related config files
        - '.woodpecker/test.yaml'
        - '.golangci.yaml'
        # go source code
        - '**/*.go'
        - 'go.*'
        # tools updates
        - Makefile
      event: pull_request

when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: *when_path

steps:
  vendor:
    image: *golang_image
    commands:
      - go mod vendor
    when:
      path:
        - <<: *when_path
        - '.woodpecker/**'

  lint-pipeline:
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - go run go.woodpecker-ci.org/woodpecker/v3/cmd/cli lint
    environment:
      WOODPECKER_DISABLE_UPDATE_CHECK: true
      WOODPECKER_LINT_STRICT: true
      WOODPECKER_PLUGINS_PRIVILEGED: 'docker.io/woodpeckerci/plugin-docker-buildx'
    when:
      - event: pull_request
        path:
          - '.woodpecker/**'

  lint:
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - make lint
    when: *when

  test:
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - make test
    when:
      - path: *when_path
