variables:
  - &golang_image 'docker.io/golang:1.24'
  - &when
    - path: &when_path # related config files
        - '.woodpecker/test.yaml'
        - '.golangci.yaml'
        # go source code
        - '**/*.go'
        - 'go.*'
        # tools updates
        - Makefile
      event: pull_request

when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
    path: *when_path

steps:
  - name: vendor
    image: *golang_image
    commands:
      - go mod vendor
    when:
      - path:
          - <<: *when_path
          - '.woodpecker/**'

  - name: lint
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - make lint
    when: *when

  - name: test
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - make test
    when:
      - path: *when_path
